exports.ORDER_TYPE = {
  MARKET: 'MARKET',
  LIMIT: 'LIMIT',
};


exports.ORDER_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED',
  COMPLETED: 'COMPLETED',
  PARTIAL_FULFILLED: 'PARTIAL_FULFILLED'
};

exports.STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};
