version: "3.9"

services:

  # Nginx Reverse Proxy
  load-balancer-external:
    image: nginx:latest
    volumes:
      - "./nginx-external.conf:/etc/nginx/nginx.conf"
    ports:
      - 8000:8000
    depends_on:
      - ms_user
      - ms_order_creation
      - ms_matching_engine
      - ms_market_data
      - ms_transaction_manager

  # RabbitMQ Service
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672" # RabbitMQ connection
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq" # persistance 
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Database Instance
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - db_data:/data/db

  # React Frontend
  react:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ms_user
      - ms_order_execution
      - ms_order_creation
      - ms_matching_engine
      - ms_market_data
      - ms_transaction_manager
    command: [ "npm", "start" ]

  # User & Auth Microservice
  ms_user:
    container_name: user
    build: ./ms_user
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Order Execution Microservice
  ms_order_execution:
    container_name: order_execution
    build: ./ms_order_execution
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Order Creation Microservice
  ms_order_creation:
    container_name: order_creation
    build: ./ms_order_creation
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./ms_shared:/app/shared
    env_file:
      - .env
    command: [ "npm", "start" ]

  # Matching Engine Microservice
  ms_matching_engine:
    container_name: matching_engine
    build: ./ms_matching_engine
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: [ "npm", "start" ]
    volumes:
      - ./ms_shared:/app/shared

  # Market Data Microservice
  ms_market_data:
    container_name: market_data
    build: ./ms_market_data
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Audit Manager Microservice
  ms_transaction_manager:
    container_name: transaction_manager
    build: ./ms_transaction_manager
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

volumes:
  db_data:
  rabbitmq_data:
