version: '3.9'

services:
  # React Frontend
  react:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - ms_user
      - ms_order_execution
      - ms_order_creation
      - ms_matching_engine
      - ms_market_data


  # User & Auth Microservice
  ms_user:
    build: ./ms_user
    image: ms_user
    ports:
      - "8001:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/db
      JWT_SECRET: your_jwt_secret_here

  # Order Execution Microservice
  ms_order_execution:
    build: ./ms_order_execution
    ports:
      - "8002:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/db

  # Order Creation Microservice
  ms_order_creation:
    build: ./ms_order_creation
    ports:
      - "8003:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/db

  # Matching Engine Microservice
  ms_matching_engine:
    build: ./ms_matching_engine
    ports:
      - "8004:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/db
      NODE_ENV: production
    command: ["npm", "start"]

  # Market Data Microservice
  ms_market_data:
    build: ./ms_market_data
    ports:
      - "8005:3000"
    environment:
      MONGO_URI: mongodb://mongodb:mongodb@mongo:27017/db

  # Audit Manager Microservice
  ms_transaction_manager:
    build: ./ms_transaction_manager
    ports:
      - "8006:3000"
    environment:
      MONGO_URI: mongodb://mongodb:mongodb@mongo:27017/db

  mongo:
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    # user_db_data:
    # order_execution_db_data:
    # order_creation_db_data:
    # matching_engine_db_data:
    # market_data_db_data: 
