# This file is an override for the default docker-compose.yml file
# It can be used to apply development changes to the docker-compose file without affecting the production environment

# If you want to bypass the override file, use the -f flag in your docker-compose command to force the use of the default file
# Example: docker-compose -f docker-compose.yml up

version: "3.9"
services:
  # This override creates a volume to map the local directory to the container directory for live updates
  # and runs the development script to start the server (nodemon)
  ms_matching_engine:
    build: ./ms_matching_engine
    volumes:
      - ./ms_matching_engine:/app
    ports:
      - "8004:3000"
    environment:
      MONGO_URI: mongodb://mongodb:mongodb@mongo:27017/db
      NODE_ENV: production
    command: ["npm", "run", "dev"]


  # This override exposes the database to host machine for debugging and manual access via a GUI tool like
  # MongoDB Compass or Robo 3T
  mongo:
    ports:
      - "27017:27017"