version: "3.9"

services:
  # React Frontend
  react:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - ms_user
      - ms_order_execution
      - ms_order_creation
      - ms_matching_engine
      - ms_market_data
      - ms_transaction_manager
    command: [ "npm", "start" ]

  # User & Auth Microservice
  ms_user:
    container_name: user
    build: ./ms_user
    image: ms_user
    ports:
      - "8001:3000"
    environment:
      BCRYPT_SALT_ROUNDS: 12
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Order Execution Microservice
  ms_order_execution:
    container_name: order_execution
    build: ./ms_order_execution
    ports:
      - "8002:3000"
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Order Creation Microservice
  ms_order_creation:
    container_name: order_creation
    build: ./ms_order_creation
    expose:
      - "3000"
    ports:
      - "8003:3000"
    volumes:
      - ./ms_shared:/app/shared
    env_file:
      - .env
    command: [ "npm", "start" ]

  # Matching Engine Microservice
  ms_matching_engine:
    container_name: matching_engine
    build: ./ms_matching_engine
    ports:
      - "8004:3000"
    env_file:
      - .env
    command: [ "npm", "start" ]
    volumes:
      - ./ms_shared:/app/shared

  # Market Data Microservice
  ms_market_data:
    container_name: market_data
    build: ./ms_market_data
    ports:
      - "8005:3000"
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  # Audit Manager Microservice
  ms_transaction_manager:
    container_name: transaction_manager
    build: ./ms_transaction_manager
    ports:
      - "8006:3000"
    env_file:
      - .env
    volumes:
      - ./ms_shared:/app/shared

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - db_data:/data/db

volumes:
  db_data:
