version: '3.9'
services:

  # React Frontend
  react:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - ms_user
      - ms_order_execution
      - ms_order_creation
      - matching_engine
      - market_data

    
  # User & Auth Microservice
  ms_user:
    build: ./ms_user
    ports:
      - "8001:3000"
    links:
      - user_db
    environment:
      MONGO_URI: mongodb://user_db:27017/ms_user_db

  user_db:
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - user_db_data:/data/db

    
  # Order Execution Microservice
  ms_order_execution:
    build: ./ms_order_execution
    ports:
      - "8002:3000"
    links:
      - order_execution_db
    environment:
      MONGO_URI: mongodb://order_execution_db:27018/order_execution_db

  order_execution_db:
    image: mongo:latest
    ports:
      - "27018"
    volumes:
      - order_execution_db_data:/data/db

  
  # Order Creation Microservice
  ms_order_creation:
    build: ./ms_order_creation
    ports:
      - "8003:3000"
    links:
      - order_creation_db
    environment:
      MONGO_URI: mongodb://order_creation_db:27019/order_creation_db

  order_creation_db:
    image: mongo:latest
    ports:
      - "27019"
    volumes:
      - order_creation_db_data:/data/db

  # Matching Engine Microservice
  matching_engine:
    build: ./matching_engine
    ports:
      - "8004:3000"
    links:
      - matching_engine_db
    environment:
      MONGO_URI: mongodb://matching_engine_db:27020/matching_engine_db

  matching_engine_db:
    image: mongo:latest
    ports:
      - "27020"
    volumes:
      - matching_engine_db_data:/data/db

  # Market Data Microservice
  market_data:
    build: ./market_data
    ports:
      - "8005:3000"
    links:
      - market_data_db
    environment:
      MONGO_URI: mongodb://market_data_db:27021/market_data_db
    
  market_data_db:
    image: mongo:latest
    ports:
      - "27021"
    volumes:
      - market_data_db_data:/data/db


volumes:
  user_db_data:
  order_execution_db_data:
  order_creation_db_data:
  matching_engine_db_data:
  market_data_db_data:
 
