FROM alpine:latest

# Set the working directory inside the container
WORKDIR /app

# Copy remaining files
COPY ./middleware/* ./shared/middleware/

# Copy remaining files
COPY ./utils/* ./shared/utils/

# Copy remaining files
COPY ./models/* ./shared/models/