FROM alpine:latest

# Set the working directory inside the container
WORKDIR /app

COPY ./middleware/* ./shared/middleware/

COPY ./models/* ./shared/models/

COPY ./lib/* ./shared/lib/

COPY ./config/* ./shared/config/