name: Docker Compose Build

on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:

  build:
    name: docker compose build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # Checkout current branch
      
    - name: Build and Run Docker Compose
      run: docker-compose up --build -d

    - name: Delay Check
      run: |
        sleep 2
        docker ps
        
    - name: Check Docker services
      run: |
        containers=$(docker ps --all --format "{{.ID}}")
        good=true
        for container in $containers; do
            name=$(docker inspect --format '{{.Name}}' "$container")
            status=$(docker inspect --format '{{.State.Status}}' "$container")
            if [ "$status" == "running" ]; then
                echo "$name is running"
            else    
                echo "$name is not running"
                service=${name#*/}  # Remove leading slash
                service=${service#*_}  # Remove prefix
                service=${service%%_1}  # Remove suffix
                service="ms_${service}"
                docker-compose logs "$service"
                good=false
            fi
        done
        if [ "$good" = false ]; then
            exit 1
        fi

    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: tests/1user_pr.jmx

    - name: Check JMeter Test Results
      run: |
        # Check if any JMeter tests failed
        if grep -q "Err:" tests/1user_pr.jtl; then
          echo "Some JMeter tests failed"
          exit 1
        else
          echo "All JMeter tests passed"
          exit 0
        fi

    - name: Tear down Docker Compose
      run: docker-compose down
