name: Docker Compose Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Check Docker services
      run: |
        services=$(docker-compose ps --services)
        good=true
        for service in $services; do
            ms=docker-compose ps -q "$service"
            if [ docker inspect --format '{{.State.Status}}' "$ms" != "running"]; then
                echo "$service is not running
                good=false
            fidocker
        done
        if [ "$good" = false ]; then
            exit 1
        fi

    - name: Tear down Docker Compose
      run: |
        docker-compose down
