name: Docker Compose Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d
        
    - name: Check Docker services
      run: |
        containers=$(docker ps --format "{{.ID}}")
        sleep 3
        good=true
        for container in $containers; do
            name=$(docker inspect --format '{{.Name}}' "$container")
            status=$(docker inspect --format '{{.State.Status}}' "$container")
            if [ "$status" == "running" ]; then
                echo "$name is running"
            else    
                echo "$name is not running"
                docker-compose logs $name
                good=false
            fi
        done
        if [ "$good" = false ]; then
            exit 1
        fi

    - name: Tear down Docker Compose
      run: |
        docker-compose down
