name: Docker Compose Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Check Docker services
      run: |
        services=$(docker-compose ps --services)
        for service in $services; do
          if [[ "$(docker inspect -f '{{.State.Running}}' "$service")" == "true" ]]; then
            echo "$service is running"
          else
            echo "$service is not running"
            exit 1
          fi
        done

    - name: Tear down Docker Compose
      run: |
        docker-compose down
