name: Docker Compose Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Delay before Tear down Docker Compose
      run: sleep 150s

    - name: Tear down Docker Compose
      run: |
        docker-compose down
