name: Docker Compose Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Microservices
      run: |
        cd ms_market_data
        npm install
        npm run build
